### ISSUE TITLE
Opensource CC

### ISSUE THREAD

**Issue by boxmaninnit** [ThatBadName/Closed-Construction#1]
I dont know how to change it into a request on mobile github.

**Comment by ThatBadName** [comment]
I'm very sorry but I am also unable to find a way. If you can maybe try on pc

**Comment by boxmaninnit** [comment]
Nevermind they dont exist I was having false memories, anyway you should open source Closed Construction as the bot has been shutdown anyway, opensourcing would allow others to  look/learn from the code or attempt to keep it updated

**Comment by boxmaninnit** [comment]
if anyone looks here for the sourcecode, its in [ThatBadName/Closed-Construction-OpenSource](https://github.com/ThatBadName/Closed-Construction-OpenSource)
